Skipping Kafka related tests in examples2 when Kafka is not available
jaegertracing/jaeger-operator pull request #1362
Opened 2021-01-13 11:30 UTC by madeelrh

2021-01-13 13:33 UTC, kevinearls requested changes
@madeelrh  This looks better, although the title is misleading.  Can you change it to something like "Permit skipping Kafka deployment"

2021-01-14 09:36 UTC, madeelrh commented
@kevinearls commit msg is updated. thanks.

2021-01-14 13:38 UTC, kevinearls approved these changes

2021-01-14 14:13 UTC, objectiser approved these changes
Based on @kevinearls review.

2021-01-14 14:13 UTC, merged