tests to verify toleration feature
jaegertracing/jaeger-operator pull request #1411
Opened 2021-03-17 01:13 UTC by jkandasa

Signed-off-by: Jeeva Kandasamy <jkandasa@gmail.com>

2021-03-17 07:22 UTC, jkandasa commented
@jpkrohling @kevinearls a test failed due to the es node not available on time. Can you please re-run the tests again?

2021-03-17 08:50 UTC, jpkrohling commented
Test restarted.

2021-03-23 08:14 UTC, jkandasa commented
@jpkrohling @kevinearls can you please review this PR?

2021-03-23 10:07 UTC, kevinearls requested changes
Please see comments.

2021-03-23 10:07 UTC, kevinearls commented on test/e2e/tolerations_test.go
> +func (suite *TolerationsTestSuite) verifyTolerations(deploymentName string, expectedList []v1.Toleration, actualList []v1.Toleration) {
I wouldn't pass in deployment name here if it's only used for debugging.  Add a logrus.Debug statement in the caller instead.

2021-03-23 11:39 UTC, jkandasa commented on test/e2e/tolerations_test.go
> +func (suite *TolerationsTestSuite) TestAllInOneTolerations() {
@kevinearls I do not see any specific request. But I see that `Tolerations` applied for all-in-one too. 
https://github.com/jaegertracing/jaeger-operator/blob/a84be509c4149ca7f7c8e37a75c4c82c21a6e1d5/pkg/apis/jaegertracing/v1/jaeger_types.go#L352

https://github.com/jaegertracing/jaeger-operator/blob/a84be509c4149ca7f7c8e37a75c4c82c21a6e1d5/pkg/apis/jaegertracing/v1/jaeger_types.go#L223

I do not want to see regression in `all-in-one`

2021-03-23 11:43 UTC, jkandasa commented on test/e2e/tolerations_test.go
> +	for expectedIndex := 0; expectedIndex < len(expectedList); expectedIndex++ {
I updated to use `range`, I do not aware of that method, nested loops in one line. Please update me, when you get it. Thanks!

2021-03-23 11:45 UTC, jkandasa commented
@kevinearls Thanks for the review. I have updated the PR based on your comments.

2021-03-24 16:11 UTC, kevinearls commented
@jkandasa  Sorry I didn't notice this earlier, but after discussing this with @jpkrohling  yesterday I was wondering if this needs to be an e2e test at all.  I wrote a unit test for this after adding the original code: https://github.com/jaegertracing/jaeger-operator/pull/1299

That test could be enhanced if I missed any cases you are covering.   Doing this in a unit test would be much cheaper than doing it in an e2e test.

2021-03-24 17:35 UTC, jkandasa commented
@kevinearls np. I believe in the unit tests we can cover this only up to CR(D) level. 
I would like to verify these changes on the deployment level.
I believe the e2e test only can do that.

2021-04-12 12:01 UTC, jkandasa commented
discussed with @jpkrohling and @kevinearls about this PR and come to know that these e2e tests covered on the unit test itself.

2021-04-12 12:01 UTC, closed without merging