Preparing relase v1.22.1
jaegertracing/jaeger-operator pull request #1432
Opened 2021-04-20 01:53 UTC by rubenvp8510

Signed-off-by: Ruben Vargas <ruben.vp8510@gmail.com>

In order to fix https://github.com/jaegertracing/jaeger-operator/issues/1426 I have to do a new release.

We forgot to bump the Jaeger version on `version.txt`

@kevinearls  @jpkrohling Could you please review?

Thanks

2021-04-20 07:20 UTC, kevinearls requested changes

2021-04-20 07:20 UTC, kevinearls commented on RELEASE.md
> +   git commit -sm "Preparing relase v1.22.1"
Please change "relase" to "release"

2021-04-21 08:08 UTC, jpkrohling commented on deploy/crds/jaegertracing.io_jaegers_crd.yaml
> +                nodePort:
Wasn't this caught during the CI process? We should fail the build if the generated files aren't synchronized.

2021-04-21 08:08 UTC, jpkrohling approved these changes

2021-04-21 08:08 UTC, merged