Use mutating webhook to inject sidecar
jaegertracing/jaeger-operator pull request #1679
Opened 2021-12-17 10:29 UTC by lujiajing1126

## Which problem is this PR solving?
- #171 
- Also #1232 

## Short description of the changes

Based on [the idiom of istio injection policy](https://istio.io/latest/docs/setup/additional-setup/sidecar-injection/#controlling-the-injection-policy), 

| Resource  | Label | Enabled value | Disabled value |
| ------------- | ------------- | ------------- | ------------- |
| Namespace | jaeger-injection | enabled | disabled |
| Pod | sidecar.jaertracing.io/inject | "true" | "false" |

This idiom could safely prevent from [bootstrapping problem](https://book.kubebuilder.io/cronjob-tutorial/running-webhook.html#the-bootstrapping-problem) supported from Kubernetes v1.15+

- `CertManager` should be installed to inject CA certification as is sugggested by [`kubebuilder-book`](https://book.kubebuilder.io/cronjob-tutorial/cert-manager.html)

## Tasks

- [x] Add webhook and minifests
- [ ] E2E tests: TBD

## To be discussed

1. Shall we totally remove namespace controller and deployment controller or just introduce this feature as an experimental thing in the next few releases keeping two kinds of injection approaches in parallel?
2. Annotation based injection is not currently supported by this webhook.

2021-12-23 15:43 UTC, lujiajing1126 commented
Though more test cases are needed and issue #1692 has to be resolved first, generally ready to be reviewed.

Request review @jpkrohling @rubenvp8510

2021-12-27 09:12 UTC, jpkrohling commented
@rubenvp8510 and @pavolloffay would be the appropriate reviewers for this.

2022-01-11 06:45 UTC, rubenvp8510 commented
I would like to get rid of namespace and deployment controllers at some point, but the only concern I have with this is it seems to be a breaking change from what the users are doing now to inject the sidecar.

Any reason to move it to Pod?  Is because it provides more flexibility?

2022-01-11 06:48 UTC, rubenvp8510 commented on .github/workflows/e2e.yaml
> +    name: Smoke E2E tests
Is this name correct? Should we call this Smoke sidecar e2e tests?

2022-01-11 06:49 UTC, rubenvp8510 commented on config/webhook/component_inject_patch.yaml
> +            - "query"
new line

2022-01-11 06:51 UTC, rubenvp8510 commented on config/webhook/kustomization.yaml
> +  - component_inject_patch.yaml
add new line at the end

2022-01-11 06:51 UTC, rubenvp8510 commented on config/webhook/namespace_inject_patch.yaml
> +          operator: DoesNotExist
new line

2022-01-11 08:01 UTC, lujiajing1126 commented
> I would like to get rid of namespace and deployment controllers at some point, but the only concern I have with this is it seems to be a breaking change from what the users are doing now to inject the sidecar.

I cannot agree more about this, "namespace and deployment controllers" have to be removed.

After migrating to the pod mutating webhook, the current injected sidecar will not be removed. Mutating webhook just provides a new way to do so which is orthogonal to the previous one. As I understand, it is the backwards compatibility guarantee.

> Any reason to move it to Pod? Is because it provides more flexibility?

I suppose there are multiple reasons, the most important of which is stable. We have met several issues in the production cluster with deployment/namespace reconciliation,

1. Issue #1696 is caused by deployment automatic reconciliation. This issue made surge in our production cluster twice, leading to thousands of pods creation within a small interval.
2. Issue #1318 is also caused by deployment reconciliation which had been fixed later.

Another issue is the upgrade: performing upgrade for the operator has to be extremely careful since it will update all deployments to inject new sidecar. It would be very scary in a relatively large cluster.

2022-01-27 18:22 UTC, rubenvp8510 commented
@lujiajing1126  Sorry for been late on this, but this PR: https://github.com/jaegertracing/jaeger-operator/pull/1718 has been merged already, I think you needed in order to test this, right?

2022-02-17 11:00 UTC, frzifus commented
hi @lujiajing1126, would you like to continue working on this topic? alternatively, i would like to continue your work.

2022-02-17 11:05 UTC, lujiajing1126 commented
> hi @lujiajing1126, would you like to continue working on this topic? alternatively, i would like to continue your work.

I am too busy to proceed on this PR. Sure please go ahead!

2022-02-24 09:27 UTC, iblancasa requested changes

2022-02-24 09:27 UTC, iblancasa commented on config/default/webhookcainjection_patch.yaml
> +#---
Is it OK to keep this commented code?

2022-02-24 09:27 UTC, iblancasa commented on pkg/inject/sidecar.go
> +	// TODO: support sidecar injection via annotation-level declaration like istio
Create an issue to address it in the future and add here the issue ID.

2022-04-06 02:11 UTC, rubenvp8510 commented
I'll close this PR , as was superseded by https://github.com/jaegertracing/jaeger-operator/pull/1828

Thanks for this PR which was used as the base for the webhook work!

2022-04-06 02:11 UTC, closed without merging