Update the operator-sdk to 1.17.0
jaegertracing/jaeger-operator pull request #1790
Opened 2022-02-24 10:41 UTC by kevinearls

Signed-off-by: Kevin Earls <kearls@redhat.com>

## Which problem is this PR solving?
- This updates the operator-sdk to 1.17.0

## Short description of the changes
- Updated the Makefile to use a newer operator-sdk

2022-02-24 10:52 UTC, pavolloffay commented
Please follow operator-sdk docs upgrading section. There are a couple of things that need to be upgraded. Here is one PR that shows migration from 1.13 to 1.17 https://github.com/open-telemetry/opentelemetry-operator/pull/692

2022-02-24 11:56 UTC, iblancasa requested changes

2022-02-24 11:56 UTC, iblancasa commented on Makefile
>  ECHO ?= @echo $(echo_prefix)
Missing version change in `bundle/tests/scorecard/config.yaml` too

2022-02-25 09:25 UTC, pavolloffay commented
The scorecard version has to be updated as well

2022-02-28 13:25 UTC, closed without merging